# Generated by Django 3.2.15 on 2024-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('Auckland', 'Auckland'), ('Bay of Plenty', 'Bay of Plenty'), ('Canterbury', 'Canterbury'), ('Gisborne', 'Gisborne'), ("Hawke's Bay", "Hawke's Bay"), ('Manawatu-Wanganui', 'Manawatu-Wanganui'), ('Marlborough', 'Marlborough'), ('Nelson', 'Nelson'), ('Northland', 'Northland'), ('Otago', 'Otago'), ('Southland', 'Southland'), ('Taranaki', 'Taranaki'), ('Tasman', 'Tasman'), ('Waikato', 'Waikato'), ('Wellington', 'Wellington'), ('West Coast', 'West Coast')], max_length=100, null=True),
        ),
    ]
