# Generated by Django 3.2.15 on 2024-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('AKL', 'Auckland'), ('BOP', 'Bay of Plenty'), ('CAN', 'Canterbury'), ('GIS', 'Gisborne'), ('HB', "Hawke's Bay"), ('MW', 'Manawatu-Wanganui'), ('MLB', 'Marlborough'), ('NEL', 'Nelson'), ('NLD', 'Northland'), ('OTA', 'Otago'), ('SLD', 'Southland'), ('TKI', 'Taranaki'), ('TAS', 'Tasman'), ('WKO', 'Waikato'), ('WEL', 'Wellington'), ('WCT', 'West Coast')], max_length=100, null=True),
        ),
    ]
